version: '3'
services:
  web:
    build: .
    volumes:
      - ./public_html:/var/www/html/
      - "./config:/docker-entrypoint-initdb.d"
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - db
    networks:
      - lamp-network
    dns:
      - 1.1.1.1
      - 1.0.0.1

  db:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: exampledb
      MYSQL_USER: exampleuser
      MYSQL_PASSWORD: examplepass
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - lamp-network
    dns:
      - 1.1.1.1
      - 1.0.0.1

  phpmyadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: db
    ports:
      - "8080:80"
    networks:
      - lamp-network
    dns:
      - 1.1.1.1
      - 1.0.0.1
volumes:
  db_data: {}

networks:
  lamp-network:
    driver: bridge
